# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 05:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.ImageField(help_text='La imagen debe tener el fondo blanco y 30 px de alto', max_length=256, upload_to='common/alliance/', verbose_name='imagen')),
                ('url', models.URLField(verbose_name='enlace')),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='posición')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
            ],
            options={
                'verbose_name_plural': 'aliados',
                'verbose_name': 'aliado',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'verbose_name': 'ciudad',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
            ],
            options={
                'verbose_name_plural': 'tipos de industria',
                'verbose_name': 'tipo de industria',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('mobile_number', models.CharField(blank=True, max_length=255, verbose_name='celular')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name_plural': 'mensajes de contacto',
                'verbose_name': 'mensaje de contacto',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('emails', models.CharField(help_text='separados por coma', max_length=300, verbose_name='correos electrónicos')),
            ],
            options={
                'verbose_name_plural': 'categorías de contacto',
                'verbose_name': 'categoría de contacto',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FixedBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='El tamaño de la imagen debe ser de 1400 x 600 pixeles', max_length=256, upload_to='common/fixedblock/', verbose_name='imagen')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(verbose_name='resumen')),
            ],
            options={
                'verbose_name_plural': 'bloques fijos',
                'verbose_name': 'bloque fijo',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ImageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=256, upload_to='common/imagelink/', verbose_name='imagen')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('section', models.CharField(choices=[('communication', 'Comunicación'), ('contact', 'Contacto'), ('home', 'Home'), ('merchandise', 'Merchandise'), ('new-equipment', 'Nuevos'), ('office-list', 'Sedes'), ('subscribe', 'Suscripción'), ('used-equipment', 'Usados')], max_length=100, verbose_name='section')),
                ('url', models.CharField(max_length=256, verbose_name='enlace')),
                ('is_external', models.BooleanField(default=False, verbose_name='enlace externo')),
                ('position', models.PositiveIntegerField(verbose_name='posición')),
            ],
            options={
                'verbose_name_plural': 'imágenes de enlace',
                'verbose_name': 'imagen de enlace',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Renta'), (2, 'Financiación'), (3, 'Gecolsa'), (4, 'Relianz')], verbose_name='categoría')),
                ('latlon', models.CharField(help_text='Bogotá es: -74.18132, 4.31454', max_length=100, validators=[django.core.validators.RegexValidator(regex='^[-+]?[0-9]*\\.?[0-9]+, [-+]?[0-9]*\\.?[0-9]+$')], verbose_name='posición')),
                ('phone', models.CharField(max_length=100, verbose_name='teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='dirección')),
                ('schedule', models.TextField(verbose_name='horario')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='common.City', verbose_name='ciudad')),
            ],
            options={
                'verbose_name_plural': 'oficinas',
                'verbose_name': 'oficina',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SliderHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_desktop', models.ImageField(help_text='2320x680 px PNG, JPG max 300 Kb', max_length=256, upload_to='common/sliderhome/', verbose_name='imagen escritorio')),
                ('image_mobile', models.ImageField(help_text='1454x920 px PNG, JPG max 300 Kb', max_length=256, upload_to='common/sliderhome/', verbose_name='imagen mobile')),
                ('image_tablet', models.ImageField(help_text='1904x680 px PNG, JPG max 300 Kb', max_length=256, upload_to='common/sliderhome/', verbose_name='imagen tablet')),
                ('url', models.CharField(max_length=256, verbose_name='enlace')),
                ('url_text', models.CharField(max_length=50, verbose_name='texto del enlace')),
                ('is_external', models.BooleanField(default=False, verbose_name='enlace externo')),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='posición')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo?')),
            ],
            options={
                'verbose_name_plural': 'sliders del home',
                'verbose_name': 'slider del home',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='WsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(blank=True, max_length=255, verbose_name='url')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='código resultado')),
                ('request_data', models.TextField(blank=True, verbose_name='envío')),
                ('answer_data', models.TextField(blank=True, verbose_name='respuesta')),
                ('ellapsed_time', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='tiempo de consulta')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name_plural': 'logs de webservices',
                'verbose_name': 'log de webservice',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ContactCategory', verbose_name='categoría'),
        ),
    ]
