# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_contact_contact_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='recipients',
            field=models.CharField(blank=True, max_length=300, verbose_name='categorias y correos'),
        ),
    ]
