# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:08
from __future__ import unicode_literals
from django.db import migrations


def populate_category(apps, schema_editor):
    Contact = apps.get_model('common', 'Contact')

    for contact in Contact.objects.all():
        title_and_email = '{} - {}'.format(
            contact.category.title,
            contact.category.emails,
        )
        contact.recipients = title_and_email
        contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_contact_recipients'),
    ]

    operations = [
        migrations.RunPython(populate_category),
    ]
