# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20170921_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.DeleteModel(
            name='ContactCategory',
        ),
    ]
