# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170921_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='full_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='URL de origen'),
        ),
    ]
