# Generated by Django 2.0.4 on 2018-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170927_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_by',
            field=models.CharField(blank=True, max_length=300, verbose_name='tipo de contacto'),
        ),
    ]
