# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 05:22
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30, unique=True, verbose_name='Identificador')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(default='/', help_text='El tamano de la imágen debe ser 500x400px', max_length=256, upload_to='cms/block/', verbose_name='Imagen del bloque.')),
                ('url', models.URLField(blank=True, help_text='E.G: http://youtube.com/', null=True, verbose_name='Link del banner')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿está activo?')),
            ],
            options={
                'verbose_name_plural': 'Bloques y Banners',
                'verbose_name': 'Bloque',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.ImageField(help_text='La imagen debe tener el tamaño de 1920x469px', max_length=256, upload_to='cms/communication/', verbose_name='imagen del banner principal')),
                ('list_image', models.ImageField(help_text='El tamano de la imágen debe ser 520x680', max_length=256, upload_to='cms/communication-list/', verbose_name='imagen para listados')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', models.TextField(verbose_name='contenido de la página')),
                ('extended_content', models.TextField(blank=True, verbose_name='contenido extendido de la página')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('event_hour', models.CharField(blank=True, max_length=15, null=True, verbose_name='hora del evento')),
                ('event_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='sitio del evento')),
                ('event_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='lugar del evento')),
                ('footer_title_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 1')),
                ('footer_link_1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 1')),
                ('footer_image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 1')),
                ('footer_title_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 2')),
                ('footer_link_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 2')),
                ('footer_image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 2')),
                ('footer_title_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 3')),
                ('footer_link_3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 3')),
                ('footer_image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 3')),
                ('meta_title', models.CharField(help_text='Máximo 55 caracteres', max_length=55)),
                ('meta_description', models.CharField(help_text='Máximo 115 caracteres', max_length=115)),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name_plural': 'comunicaciones',
                'verbose_name': 'comunicación',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommunicationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('position', models.PositiveIntegerField(unique=True, verbose_name='posición')),
                ('has_comments', models.BooleanField(default=False, verbose_name='Comentarios habilitados')),
                ('has_share_buttons', models.BooleanField(default=False, verbose_name='Botones de compartir habilitados')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('footer_title_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 1')),
                ('footer_link_1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 1')),
                ('footer_image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 1')),
                ('footer_title_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 2')),
                ('footer_link_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 2')),
                ('footer_image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 2')),
                ('footer_title_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 3')),
                ('footer_link_3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 3')),
                ('footer_image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 3')),
            ],
            options={
                'verbose_name_plural': 'categorías de comunicación',
                'verbose_name': 'categoría de comunicación',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CommunicationGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.ImageField(max_length=256, upload_to='cms/communicationgallery/', verbose_name='imagen')),
                ('position', models.PositiveIntegerField(verbose_name='posición')),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cms.Communication')),
            ],
            options={
                'verbose_name_plural': 'galerías de imágenes',
                'verbose_name': 'galería de imágenes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='CommunicationRelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.FileField(max_length=256, upload_to='cms/communication-relatedfile/', verbose_name='archivo')),
                ('show_icon', models.BooleanField(default=False, verbose_name='mostrar ícono en lugar de enlace')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_files', to='cms.Communication')),
            ],
            options={
                'verbose_name_plural': 'archivos relacionados',
                'verbose_name': 'archivo relacionado',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Texto corto')),
                ('url', models.URLField(verbose_name='Enlace')),
                ('is_external', models.BooleanField(default=False, verbose_name='Es un enlace externo')),
                ('image', models.ImageField(help_text='El tamano de la imágen debe ser 1120x400px', max_length=256, upload_to='cms/featured-content/', verbose_name='Imagen del contenido destacado')),
            ],
            options={
                'verbose_name_plural': 'Contenidos destacados del Home',
                'verbose_name': 'Contenido destacados del Home',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.ImageField(max_length=256, upload_to='cms/gallery/', verbose_name='imagen')),
                ('position', models.PositiveIntegerField(verbose_name='posición')),
            ],
            options={
                'verbose_name_plural': 'galerías de imágenes',
                'verbose_name': 'galería de imágenes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('summary', models.TextField(verbose_name='resumen para el header')),
                ('image', models.ImageField(help_text='El tamano de la imágen debe ser 1920x469px', max_length=256, upload_to='cms/page/', verbose_name='imagen del banner principal')),
                ('list_image', models.ImageField(help_text='El tamano de la imágen debe ser 320x410px', max_length=256, upload_to='cms/page-list/', verbose_name='imagen para listados')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('position', models.PositiveIntegerField(verbose_name='posición')),
                ('content', models.TextField(blank=True, verbose_name='contenido de la página')),
                ('has_children_accordion', models.BooleanField(default=False, verbose_name='muestra menú lateral')),
                ('show_children', models.BooleanField(default=True, verbose_name='mostrar hijos')),
                ('footer_title_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 1')),
                ('footer_link_1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 1')),
                ('footer_image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 1')),
                ('footer_title_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 2')),
                ('footer_link_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 2')),
                ('footer_image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 2')),
                ('footer_title_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título 3')),
                ('footer_link_3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Enlace interno 3')),
                ('footer_image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen 3')),
                ('meta_title', models.CharField(help_text='Máximo 55 caracteres', max_length=55)),
                ('meta_description', models.CharField(help_text='Máximo 115 caracteres', max_length=115)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='actualizado en')),
                ('is_active', models.BooleanField(default=False, verbose_name='¿está activa?')),
                ('has_contact', models.BooleanField(default=False, verbose_name='¿tiene contacto?')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.Page', verbose_name='página padre')),
            ],
            options={
                'verbose_name_plural': 'páginas',
                'verbose_name': 'página',
                'ordering': ('-parent_id', 'position'),
            },
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('image', models.FileField(max_length=256, upload_to='cms/relatedfile/', verbose_name='archivo')),
                ('show_icon', models.BooleanField(default=False, verbose_name='mostrar ícono en lugar de enlace')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_files', to='cms.Page')),
            ],
            options={
                'verbose_name_plural': 'archivos relacionados',
                'verbose_name': 'archivo relacionado',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('url', models.URLField(verbose_name='enlace')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='cms.Page')),
            ],
            options={
                'verbose_name_plural': 'enlaces relacionados',
                'verbose_name': 'enlace relacionado',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='SatelliteMonitoringContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre completo')),
                ('company', models.CharField(max_length=100, verbose_name='empresa')),
                ('email', models.EmailField(max_length=100, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=100, verbose_name='teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='dirección')),
                ('machine', models.CharField(help_text='Mencione al menos una serie de máquina que desea         monitorear', max_length=100, verbose_name='tipo de máquina')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'solicitudes de monitoreo',
                'verbose_name': 'monitoreo satelital',
                'ordering': ('-created_at', 'name'),
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cms.Page'),
        ),
        migrations.AddField(
            model_name='communication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CommunicationCategory', verbose_name='categoría'),
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
            ],
            options={
                'verbose_name_plural': 'eventos',
                'verbose_name': 'evento',
                'ordering': ['-created_at'],
                'proxy': True,
            },
            bases=('cms.communication',),
        ),
        migrations.CreateModel(
            name='CommunicationNews',
            fields=[
            ],
            options={
                'verbose_name_plural': 'comunicación',
                'verbose_name': 'comunicaciones',
                'ordering': ['-created_at'],
                'proxy': True,
            },
            bases=('cms.communication',),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('position', 'parent')]),
        ),
    ]
