# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='has_contact',
            field=models.BooleanField(default=False, verbose_name='¿tiene contacto?'),
        ),
    ]
