# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_communication_has_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='footer_image_1',
            field=models.ImageField(blank=True, help_text='El tamano de la imágen debe ser 991x122', null=True, upload_to='', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='footer_image_2',
            field=models.ImageField(blank=True, help_text='El tamano de la imágen debe ser 991x122', null=True, upload_to='', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='footer_image_3',
            field=models.ImageField(blank=True, help_text='El tamano de la imágen debe ser 991x122', null=True, upload_to='', verbose_name='Imagen 3'),
        ),
    ]
