# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170124_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='has_contact',
        ),
    ]
