# Generated by Django 2.0.5 on 2018-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_page_has_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video_url',
            field=models.URLField(blank=True, help_text='Debe ser un video de youtube. Ej: https://www.youtube.com/watch?v=697EbMJei_Q', verbose_name='url de video de la página'),
        ),
    ]
