# Generated by Django 2.0.7 on 2019-09-24 17:08

import app.storages
import app.validators
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_complaint', models.PositiveSmallIntegerField(choices=[(10, 'Si'), (20, 'No')], default=10, verbose_name='¿la denuncia se realizará de manera anónima?')),
                ('full_name', models.CharField(blank=True, max_length=80, verbose_name='nombres y apellidos')),
                ('email', models.EmailField(blank=True, help_text='Máximo 100 caracteres', max_length=60, verbose_name='correo electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='Ingresa solo números'), django.core.validators.MinLengthValidator(10, message='Asegurate que tenga al menos 10 caracteres')], verbose_name='Número de contacto')),
                ('company_relation', models.PositiveSmallIntegerField(choices=[(10, 'Empleado(a)'), (20, 'Cliente'), (30, 'Proveedor'), (40, 'Contratista'), (50, 'Otro')], verbose_name='vínculo con la compañía')),
                ('other_relation', models.CharField(blank=True, max_length=100, verbose_name='¿Cuál?')),
                ('purpose', models.CharField(max_length=100, verbose_name='objeto de la denuncia')),
                ('date', models.DateField(verbose_name='fecha de los hechos')),
                ('place', models.CharField(max_length=100, verbose_name='lugar de los hechos')),
                ('acts', models.TextField(help_text='Identificar si los hechos están por suceder', verbose_name='hechos de la denuncia')),
                ('people_complaint', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None, verbose_name='persona(s) denunciada(s)')),
                ('document', models.FileField(blank=True, help_text='máximo 2MB', null=True, upload_to=app.storages.get_upload_path, validators=[app.validators.FileSizeValidator(2000)], verbose_name='documento adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'queja',
                'verbose_name_plural': 'quejas y reclamos',
                'ordering': ['-id'],
            },
        ),
    ]
