ANONYMOUS_CHOICE = 10
NOT_ANONYMOUS_CHOICE = 20
TYPE_COMPLAINT_CHOICES = (
    (ANONYMOUS_CHOICE, 'Sí'),
    (NOT_ANONYMOUS_CHOICE, 'No'),
)

EMPLOYEE_CHOICE = 10
CUSTOMER_CHOICE = 20
PROVIDER_CHOICE = 30
CONTRACTOR_CHOICE = 40
OTHER_CHOICE = 50

COMPANY_RELATION_CHOICES = (
    (EMPLOYEE_CHOICE, 'Empleado(a)'),
    (CUSTOMER_CHOICE, 'Cliente'),
    (PROVIDER_CHOICE, 'Proveedor'),
    (CONTRACTOR_CHOICE, 'Contratista'),
    (OTHER_CHOICE, 'Otro'),
)
